# -*- coding: utf-8 -*-
"""
Created on Mon Nov 29 11:14:49 2021

@author: bpeterson
"""

Rosalind = "CGGCGCCGTGATTAGCAACCACACGGTAAGTAAAGTCTCTGATCGCTGAGGAACATAGCCTAACGCAGTACGGTGCCTCTTGTTGTTGATCCTTGTCCAAGACTTAAACCCTAGCGGCCCGAGCCAAAACTGGTTATTTTCTAGCAGTCGAGCGTTTGGGTAAAATGGGTCATACGAAGACACAGTGCCGAGGAATACGTGACTCAAGCATGGTGGACAATCACACGGCAGACTTAGCGGGAGGATATAGACCAGGACGGCCGCCACGCGGTGAGCTAGAAGTATCCCGCAATGAAATTTGGAGAATAGGGTTCGCAAAATACCTTGCGCTTGGCAGTATGCGCAATGTTGTCGGGTCGCGCACAATAATGTAGGATAACGGTTTCCCGGGAGAGTTACTATCCCCGAGACTAGATAAACACTGGGCGTTAACGTTTTTACTCGGATTGAAACCCATTAATTGGGGAGGGTCGGTTTAGGCGTGGAAGCGCGGGACCTGAATTAGCGTTAACATGACAGAGAATTCAACCTAGTTGTAGGTCGCCGCTGGCTTTCCGGCTCCTGCTGAGTCAATGAGAATTACAGCACCAGACTCGATGAGTCAAATGTCCCCTACGATATCTGTGTAGACTAACTTTATCTAAATGCTGCCAATGACCTGATCCTCTTATGCCGCATGTTGCCCACTGGTCTCTAATTCGAATGGTTAGTATAAGGTACGCGATTATCTCAAGGGCGATGACAGCTCGCGATGGGTAAGCTAACGATGGGACAACGCGGGCTAGTATCTGATGCTTCTAATGAAGAAAGGTCGGACCTGTGGGGAGTGTGTGGTGCGTACGTAGTTATCTAG"
Test = "AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC"
DNA = iter(Rosalind)



def count_bases(sequence):
#Counts nucleotides in a given sequence, with the output format of A C G T in that order.
    A_count = 0
    C_count = 0
    G_count = 0
    T_count = 0

    for base in sequence:
        if base == "A":
            A_count = A_count + 1
        elif base == "G":
            G_count = G_count + 1
        elif base == "C":
            C_count = C_count + 1
        elif base == "T":
            T_count = T_count + 1
    print(A_count, C_count, G_count, T_count)



count_bases(Rosalind)
